Use [LibraryDB]

IF OBJECT_ID('Users') IS NOT NULL
DROP TABLE Users;

IF OBJECT_ID('Loans') IS NOT NULL
DROP TABLE Loans;

IF OBJECT_ID('Books') IS NOT NULL
DROP TABLE Books;

IF OBJECT_ID('LibraryBooks') IS NOT NULL
DROP TABLE LibraryBooks;

CREATE TABLE Users
(
	userId INT NOT NULL IDENTITY PRIMARY KEY,
	username VARCHAR(32) NOT NULL,
	userPw VARCHAR(32) NOT NULL,
);

CREATE TABLE Loans
(
	userId INT NOT NULL,
	bookId INT NOT NULL,
	dueDate DATE NOT NULL,
);

CREATE TABLE Books
(
	isbn VARCHAR(20) NOT NULL PRIMARY KEY,
	title VARCHAR(255) NOT NULL,
	authors VARCHAR(255) NOT NULL,
);

CREATE TABLE LibraryBooks
(
	bookId INT NOT NULL IDENTITY PRIMARY KEY,
	isbn VARCHAR(20) NOT NULL,
);
